import type { JourneyDefinition } from "../types";
import { registerJourney } from "./index";

const journey: JourneyDefinition = {
  id: "guest-order",
  title: "Placing Your First Guest Order",
  description: "Learn how to place an order without creating an account, using M-Pesa.",
  version: 1,
  autoStart: false,
  steps: [
    {
      id: "guest-start",
      journeyId: "guest-order",
      title: "Start Ordering",
      description: "Click on any service or use the catalogue below to browse available platforms.",
      target: "walkthrough-service-catalog",
      placement: "bottom",
      route: "/services",
      condition: () => typeof window !== "undefined" && window.location.pathname.startsWith("/services"),
      nextBehaviour: "action",
      actionExpectation: "click",
    },
    {
      id: "guest-quantity",
      journeyId: "guest-order",
      title: "Set Quantity",
      description: "Enter the quantity you need. Minimums and maximums are shown to help you choose.",
      target: "walkthrough-quantity-input",
      placement: "right",
      route: "/order",
      skipOnMobile: true,
      nextBehaviour: "action",
      actionExpectation: "input",
    },
    {
      id: "guest-target",
      journeyId: "guest-order",
      title: "Enter Your Target Link",
      description: "Paste the URL of the post, profile, or video you want to promote.",
      target: "walkthrough-target-link",
      placement: "right",
      nextBehaviour: "action",
      actionExpectation: "input",
    },
    {
      id: "guest-checkout",
      journeyId: "guest-order",
      title: "Guest Checkout",
      description: "No account needed. Select 'Continue as Guest' to proceed with phone verification.",
      target: "walkthrough-guest-checkout",
      placement: "bottom",
      nextBehaviour: "action",
      actionExpectation: "click",
    },
    {
      id: "guest-phone",
      journeyId: "guest-order",
      title: "Enter Phone Number",
      description: "Your M-Pesa number. This must match the number you'll use for payment.",
      target: "walkthrough-phone-input",
      placement: "right",
      nextBehaviour: "action",
      actionExpectation: "input",
    },
    {
      id: "guest-pay",
      journeyId: "guest-order",
      title: "Complete Payment",
      description: "Confirm the amount shown. The server-calculated amount includes a KES 7 service charge and is final.",
      target: "walkthrough-mpesa-pay",
      placement: "top",
      nextBehaviour: "action",
      actionExpectation: "click",
    },
    {
      id: "guest-track",
      journeyId: "guest-order",
      title: "Track Your Order",
      description: "Check your phone for the STK prompt, then return here to track your order's progress.",
      nextBehaviour: "manual",
    },
  ],
  allowSkip: true,
};

registerJourney(journey);
