export const PLATFORMS = [
  {
    id: "youtube",
    name: "YouTube",
    icon: "📺",
    color: "bg-red-600",
    href: "/order/youtube",
    description: "High-retention Views, Monetizable Subscribers, Instant Likes",
    services: [
      { name: "High-retention Views", href: "/order/youtube-views" },
      { name: "Monetizable Subscribers", href: "/order/youtube-subscribers-2/26252" },
      { name: "Instant Likes", href: "/order/youtube-likes" },
      { name: "AI-Generated Comments", href: "/order/youtube-ai-generated-comment-boost-ranking-amp-interaction" },
      { name: "Watch Time", href: "/order/youtube-watch-time" },
    ],
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    icon: "🟢",
    color: "bg-green-500",
    href: "/order/whatssapp",
    description: "Channel Members, Status Views, Group Engagement Packs",
    services: [
      { name: "Channel Members", href: "/order/whatssapp" },
      { name: "Status Views", href: "/order/whatssapp" },
      { name: "Group Engagement Packs", href: "/order/whatssapp" },
      { name: "Channel Followers", href: "/order/whatsapp-channel-followers" },
      { name: "Poll Votes", href: "/order/whatsapp-poll-votes" },
      { name: "Channel Post Reactions", href: "/order/whatsapp-channel-post-reactions-instant-server-complete-in-1-minute" },
      { name: "Channel Post Reactions [Cheap Slow Server]", href: "/order/whatsapp-channel-post-reactions-cheap-slow-server" },
      { name: "Channel Auto Future Post Reactions", href: "/order/whatsapp-channel-auto-future-post-reactions" },
    ],
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: "📸",
    color: "bg-gradient-to-tr from-yellow-400 via-red-500 to-purple-600",
    href: "/order?category=instagram",
    description: "Followers [Refill/Country Targeted], Likes, Comments, Reels Views",
    services: [
      { name: "Followers [Refill]", href: "/order?category=instagram" },
      { name: "Country Targeted Followers", href: "/order?category=instagram" },
      { name: "Likes", href: "/order?category=instagram" },
      { name: "Comments", href: "/order?category=instagram" },
      { name: "Reels Views", href: "/order?category=instagram" },
    ],
  },
  {
    id: "facebook",
    name: "Facebook",
    icon: "💙",
    color: "bg-blue-600",
    href: "/order?category=facebook",
    description: "Page Followers, Profile Likes, Post Reactions, Video Views",
    services: [
      { name: "Page Followers", href: "/order?category=facebook" },
      { name: "Profile Likes", href: "/order?category=facebook" },
      { name: "Post Reactions", href: "/order?category=facebook" },
      { name: "Video Views", href: "/order?category=facebook" },
    ],
  },
  {
    id: "tiktok",
    name: "TikTok",
    icon: "🎵",
    color: "bg-black border border-kenya-white",
    href: "/order?category=tiktok",
    description: "Views [KES 10 tu promo], Non-Drop Followers, Live Stream Viewers",
    services: [
      { name: "Views [KES 10 tu]", href: "/order?category=tiktok" },
      { name: "Non-Drop Followers", href: "/order?category=tiktok" },
      { name: "Live Stream Viewers", href: "/order?category=tiktok" },
    ],
  },
  {
    id: "telegram",
    name: "Telegram",
    icon: "✈️",
    color: "bg-sky-500",
    href: "/order?category=telegram",
    description: "Channel/Group Members, Post Views, Poll Votes",
    services: [
      { name: "Channel Members", href: "/order?category=telegram" },
      { name: "Group Members", href: "/order?category=telegram" },
      { name: "Post Views", href: "/order?category=telegram" },
      { name: "Poll Votes", href: "/order?category=telegram" },
    ],
  },
  {
    id: "google-maps",
    name: "Google Maps Reviews",
    icon: "📍",
    color: "bg-green-600",
    href: "/order?category=google-maps",
    description: "5-Star Custom Reviews, Local Guide Feedback, Place Saves & Directions",
    services: [
      { name: "5-Star Custom Reviews", href: "/order?category=google-maps" },
      { name: "Local Guide Feedback", href: "/order?category=google-maps" },
      { name: "Place Saves & Directions", href: "/order?category=google-maps" },
    ],
  },
  {
    id: "x-twitter",
    name: "X (Twitter)",
    icon: "🖤",
    color: "bg-black border border-kenya-white",
    href: "/order?category=x-twitter",
    description: "Complete X/Twitter growth suite",
    services: [
      { name: "Comments & Crypto Bot", href: "/order?category=x-twitter" },
      { name: "Crypto & NFT Followers", href: "/order?category=x-twitter" },
      { name: "Favorites / Likes", href: "/order?category=x-twitter" },
      { name: "Followers [Refill]", href: "/order?category=x-twitter" },
      { name: "Live Viewers", href: "/order?category=x-twitter" },
      { name: "Mentions", href: "/order?category=x-twitter" },
      { name: "Nigeria Followers & Retweets", href: "/order?category=x-twitter" },
      { name: "Poll Votes", href: "/order?category=x-twitter" },
      { name: "Retweets", href: "/order?category=x-twitter" },
      { name: "Space Listeners", href: "/order?category=x-twitter" },
      { name: "Stats & Clicks", href: "/order?category=x-twitter" },
      { name: "Views Country Targeted", href: "/order?category=x-twitter" },
    ],
  },
];

export const ORDER_SERVICES = [
  {
    id: "yt-views",
    categoryId: "youtube",
    name: "YT1 YouTube Views [High Retention / Monetizable]",
    serviceId: "YT_VIEW_01",
    min: 100,
    max: 1000000,
    rate: 0.45,
    refill: "30 Days Refill Guarantee",
    description: "High-retention views with longer watch time. Best for monetizable content. Account must be public before placing order.",
    requiresLink: true,
    requiresComments: false,
    speed: "up to 50k views/day",
    startTime: "0-1 hours",
    notice: "Ensure video is public and embedding is enabled before placing order. Do not change link while processing.",
    monetizable: true,
  },
  {
    id: "yt-subs",
    categoryId: "youtube",
    name: "YT2 YouTube Subscribers [Non-Drop / Refill Guarantee]",
    serviceId: "YT_SUB_02",
    min: 50,
    max: 10000,
    rate: 3.50,
    refill: "30 Days Refill Guarantee",
    description: "Real monetizable subscribers with high retention. Non-drop guarantee. Please use a public channel link.",
    requiresLink: true,
    requiresComments: false,
    speed: "1k/day",
    startTime: "0-2 hours",
    notice: "Channel must be public. Do not change channel link while processing.",
    monetizable: true,
  },
  {
    id: "yt-likes",
    categoryId: "youtube",
    name: "YT3 YouTube Likes [Instant Delivery / Real Profiles]",
    serviceId: "YT_LIKE_03",
    min: 20,
    max: 50000,
    rate: 0.85,
    refill: "30 Days Refill Guarantee",
    description: "Instant likes delivered within minutes. Works on any public video link.",
    requiresLink: true,
    requiresComments: false,
    speed: "5k/day",
    startTime: "0-30 minutes",
    notice: "Video must be public. Do not change link while processing.",
    monetizable: false,
  },
  {
    id: "ytv1",
    categoryId: "youtube-views",
    name: "YTV1 YouTube Views [High Retention / Monetizable]",
    serviceId: "YT_VIEW_01",
    min: 100,
    max: 1000000,
    rate: 0.45,
    refill: "30 Days Refill Guarantee",
    description: "High-retention views with longer watch time. Best for monetizable content. Account must be public before placing order.",
    requiresLink: true,
    requiresComments: false,
    speed: "up to 50k views/day",
    startTime: "0-1 hours",
    notice: "Ensure video is public and embedding is enabled before placing order. Do not change link while processing.",
    monetizable: true,
  },
  {
    id: "ytv2",
    categoryId: "youtube-views",
    name: "YTV2 YouTube Views [Fast Speed / Non-Drop]",
    serviceId: "YT_VIEW_FAST",
    min: 500,
    max: 5000000,
    rate: 0.38,
    refill: "30 Days Refill Guarantee",
    description: "Fast-delivery views with non-drop guarantee. High-speed campaign suitable for viral content. Video must be public.",
    requiresLink: true,
    requiresComments: false,
    speed: "up to 100k views/day",
    startTime: "0-2 hours",
    notice: "Ensure video is public, embedding is enabled, and age restriction is turned off before placing your views order.",
    monetizable: false,
  },
  {
    id: "ytv3",
    categoryId: "youtube-views",
    name: "YTV3 YouTube Shorts Views [Instant Delivery]",
    serviceId: "YT_SHORTS_VIEW",
    min: 100,
    max: 10000000,
    rate: 0.15,
    refill: "No refill",
    description: "Instant delivery views specifically for YouTube Shorts. High-volume campaign optimized for short-form content. Short must be public.",
    requiresLink: true,
    requiresComments: false,
    speed: "up to 500k views/day",
    startTime: "0-30 minutes",
    notice: "Ensure video is public, embedding is enabled, and age restriction is turned off before placing your views order. Shorts links only.",
    monetizable: false,
  },
  {
    id: "ytl1",
    categoryId: "youtube-likes",
    name: "YTL1 YouTube Likes [Instant Delivery / Real Profiles]",
    serviceId: "26041",
    min: 20,
    max: 50000,
    rate: 0.85,
    refill: "30 Days Refill Guarantee",
    description: "Instant likes delivered within minutes from real profiles. High-quality accounts with profile pictures. Video must be public.",
    requiresLink: true,
    requiresComments: false,
    speed: "5k/day",
    startTime: "0-30 minutes",
    notice: "Ensure the video like counter is set to public. Do not hide likes or private the video while order is actively processing.",
  },
  {
    id: "ytl2",
    categoryId: "youtube-likes",
    name: "YTL2 YouTube Likes [High Quality / Stable Retention]",
    serviceId: "YT_LIKE_HQ",
    min: 50,
    max: 20000,
    rate: 1.10,
    refill: "30 Days Refill Guarantee",
    description: "High-quality likes with stable retention. Real accounts with long-term activity. Best for maintaining engagement metrics.",
    requiresLink: true,
    requiresComments: false,
    speed: "10k/day",
    startTime: "0-1 hours",
    notice: "Ensure the video like counter is set to public. Do not hide likes or private the video while order is actively processing.",
  },
  {
    id: "ytl3",
    categoryId: "youtube-likes",
    name: "YTL3 YouTube Shorts Likes [Instant Speed]",
    serviceId: "YT_SHORTS_LIKE",
    min: 50,
    max: 100000,
    rate: 0.50,
    refill: "No refill",
    description: "Instant likes specifically for YouTube Shorts. High-speed delivery optimized for short-form content. Short must be public.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-15 minutes",
    notice: "Ensure the video like counter is set to public. Do not hide likes or private the video while order is actively processing. Shorts links only.",
  },
  {
    id: "yt-ai-c1",
    categoryId: "youtube-ai-generated-comment-boost-ranking-amp-interaction",
    name: "YT_AI_C1 YouTube AI Contextual Comments [Algorithm & SEO Boost]",
    serviceId: "26078",
    min: 10,
    max: 5000,
    rate: 14.00,
    refill: "30 Days Refill Guarantee",
    description: "Contextually relevant AI comments engineered to trigger YouTube's recommendation algorithm. Perfect for SEO boost and ranking improvement. Video comments must be public.",
    requiresLink: true,
    requiresComments: true,
    speed: "1k/day",
    startTime: "0-2 hours",
    notice: "Contextually relevant comments designed to trigger YouTube's recommendation engine. Ensure video comments are set to public before submitting order.",
  },
  {
    id: "yt-ai-c2",
    categoryId: "youtube-ai-generated-comment-boost-ranking-amp-interaction",
    name: "YT_AI_C2 YouTube Smart AI Comments [Engagement & Reply Thread Pack]",
    serviceId: "26080",
    min: 20,
    max: 10000,
    rate: 16.50,
    refill: "30 Days Refill Guarantee",
    description: "Advanced AI comment packs built for long thread engagement and high algorithm interaction. Smart contextual replies that boost video engagement metrics.",
    requiresLink: true,
    requiresComments: true,
    speed: "2k/day",
    startTime: "0-2 hours",
    notice: "Advanced AI comment packs built for long thread engagement and high algorithm interaction. Ensure video comments are set to public before submitting order.",
  },
  {
    id: "ytw1",
    categoryId: "youtube-watch-time",
    name: "YTW1 YouTube Monetization Watch Hours [High Retention / Long Video]",
    serviceId: "26256",
    min: 100,
    max: 4000,
    rate: 45.00,
    refill: "30 Days Refill Guarantee",
    description: "High-retention watch hours optimized for YouTube Partner Program. Designed for long-form videos (60 min+). Fast delivery at 500 hours/day.",
    requiresLink: true,
    requiresComments: false,
    speed: "500 hours/day",
    startTime: "0-24 hours",
    notice: "Target video must be at least 60 minutes long for optimal watch time accumulation. Ensure video is public and unlisted/private mode is disabled during fulfillment of order.",
  },
  {
    id: "ytw2",
    categoryId: "youtube-watch-time",
    name: "YTW2 YouTube Monetization Watch Hours [Standard Speed / 15-Min+ Videos]",
    serviceId: "26255",
    min: 50,
    max: 4000,
    rate: 38.00,
    refill: "30 Days Refill Guarantee",
    description: "Standard-speed watch hours for monetization-ready channels. Works with videos 15 minutes and above. Reliable 300 hours/day delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "300 hours/day",
    startTime: "0-24 hours",
    notice: "Target video must be at least 15 minutes long. Ensure video is public and unlisted/private mode is disabled during fulfillment of order.",
  },
  {
    id: "ytw3",
    categoryId: "youtube-watch-time",
    name: "YTW3 YouTube Monetization Watch Hours [Fast Start / Mixed Duration]",
    serviceId: "26254",
    min: 50,
    max: 4000,
    rate: 34.00,
    refill: "30 Days Refill Guarantee",
    description: "Fast-start watch hours with mixed duration support. Suitable for videos 10 minutes and above. High-speed delivery at 400 hours/day.",
    requiresLink: true,
    requiresComments: false,
    speed: "400 hours/day",
    startTime: "0-12 hours",
    notice: "Suitable for videos 10 minutes and above. Ensure video is public and unlisted/private mode is disabled during fulfillment of order.",
  },
  {
    id: "yt-subs",
    categoryId: "youtube-subscribers-2",
    name: "YTS1 YouTube Subscribers [Non-Drop / Refill 30 Days]",
    serviceId: "26252",
    min: 50,
    max: 10000,
    rate: 3.50,
    refill: "30 Days Refill Guarantee",
    description: "Real non-drop subscribers with 30-day refill guarantee. High retention. Please use a public channel link.",
    requiresLink: true,
    requiresComments: false,
    speed: "1k/day",
    startTime: "0-12 hours",
    notice: "Channel subscriber count must be public. Do not hide your subscriber count or change the channel handle while the order is processing.",
  },
  {
    id: "yts2",
    categoryId: "youtube-subscribers-2",
    name: "YTS2 YouTube Subscribers [High Quality / Fast Start]",
    serviceId: "YT_SUB_FAST",
    min: 100,
    max: 5000,
    rate: 4.20,
    refill: "60 Days Refill Guarantee",
    description: "High-quality subscribers with fast start. Real accounts with profile pictures. Channel must be public.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-6 hours",
    notice: "Channel subscriber count must be public. Do not hide your subscriber count or change the channel handle while the order is processing.",
  },
  {
    id: "yts3",
    categoryId: "youtube-subscribers-2",
    name: "YTS3 YouTube Subscribers [Monetization Ready / Lifetime Guarantee]",
    serviceId: "YT_SUB_LIFE",
    min: 50,
    max: 25000,
    rate: 6.80,
    refill: "Lifetime Refill Guarantee",
    description: "Premium monetization-ready subscribers with lifetime refill guarantee. Highest quality retention. Channel must be public.",
    requiresLink: true,
    requiresComments: false,
    speed: "500/day",
    startTime: "0-24 hours",
    notice: "Channel subscriber count must be public. Do not hide your subscriber count or change the channel handle while the order is processing.",
  },
  {
    id: "wa-members",
    categoryId: "whatsapp",
    name: "WA1 WhatsApp Channel Followers [Instant / Non-Drop]",
    serviceId: "WA_CHAN_01",
    min: 100,
    max: 10000,
    rate: 2.50,
    refill: "30 Days Refill Guarantee",
    description: "Instant channel followers with non-drop guarantee. Real WhatsApp accounts. Channel must be public and invite link active.",
    requiresLink: true,
    requiresComments: false,
    speed: "5k/day",
    startTime: "0-2 hours",
    notice: "Ensure your WhatsApp channel invite link is public and active before submitting order. Do not reset or revoke the invite link during fulfillment.",
  },
  {
    id: "wa-status",
    categoryId: "whatsapp",
    name: "WA2 WhatsApp Status Views [Real Contacts / Fast Delivery]",
    serviceId: "WA_STATUS_02",
    min: 50,
    max: 5000,
    rate: 0.80,
    refill: "No refill",
    description: "Real status views from active contacts. Fast delivery within minutes. Works on all public status updates.",
    requiresLink: true,
    requiresComments: false,
    speed: "10k/day",
    startTime: "0-30 minutes",
    notice: "Ensure your WhatsApp status is public and active. Views are delivered from real accounts.",
  },
  {
    id: "wa-group",
    categoryId: "whatsapp",
    name: "WA3 WhatsApp Group Members [Active Engagement Pack]",
    serviceId: "WA_GROUP_03",
    min: 50,
    max: 2000,
    rate: 4.00,
    refill: "30 Days Refill Guarantee",
    description: "Active group members with real engagement. Non-drop guarantee. Group must allow join requests or be public.",
    requiresLink: true,
    requiresComments: false,
    speed: "1k/day",
    startTime: "0-12 hours",
    notice: "Ensure your WhatsApp group invite link is public and active before submitting order. Do not reset or revoke the invite link during fulfillment.",
  },
  {
    id: "wapv1",
    categoryId: "whatsapp-poll-votes",
    name: "WAPV1 WhatsApp Poll Votes [Instant Delivery / Real Numbers]",
    serviceId: "26244",
    min: 20,
    max: 5000,
    rate: 3.00,
    refill: "No refill",
    description: "Instant poll votes from real numbers. Fast delivery within minutes. Perfect for quick polls and surveys.",
    requiresLink: true,
    requiresComments: false,
    speed: "5k/day",
    startTime: "0-30 minutes",
    notice: "Ensure the WhatsApp group or channel poll is active and accessible. Clearly specify your target option number or exact poll choice in the notes/extra field if applicable.",
  },
  {
    id: "wapv2",
    categoryId: "whatsapp-poll-votes",
    name: "WAPV2 WhatsApp Group Poll Votes [Targeted Option Selection]",
    serviceId: "26245",
    min: 50,
    max: 10000,
    rate: 4.50,
    refill: "No refill",
    description: "Targeted poll votes for specific option selection. High-speed delivery for group polls and contests.",
    requiresLink: true,
    requiresComments: false,
    speed: "10k/day",
    startTime: "0-2 hours",
    notice: "Advanced group poll voting engineered for precise option selection. Make sure the WhatsApp group link is fully accessible and specify your target choice clearly before submitting order.",
  },
  {
    id: "wapv3",
    categoryId: "whatsapp-poll-votes",
    name: "WAPV3 WhatsApp Premium Poll Votes [Kenyan Verified Numbers / High Retention]",
    serviceId: "26246",
    min: 30,
    max: 15000,
    rate: 6.00,
    refill: "30 Days Refill Guarantee",
    description: "Premium local tier utilizing authentic Kenyan user profiles to drive verified poll engagement. High retention with refill guarantee.",
    requiresLink: true,
    requiresComments: false,
    speed: "8k/day",
    startTime: "0-2 hours",
    notice: "Premium local tier utilizing authentic Kenyan user profiles to drive verified poll engagement. Ensure the group invite link remains active and public during fulfillment of order.",
  },
  {
    id: "wapv4",
    categoryId: "whatsapp-poll-votes",
    name: "WAPV4 WhatsApp Ultimate Turbo Poll Votes [Instant Bulk Execution]",
    serviceId: "26247",
    min: 50,
    max: 25000,
    rate: 7.50,
    refill: "30 Days Refill Guarantee",
    description: "Ultra-high speed bulk poll voting tier designed for massive contests and elections. Turbo delivery at 15k votes/day.",
    requiresLink: true,
    requiresComments: false,
    speed: "15k/day",
    startTime: "0-12 hours",
    notice: "Ultra-high speed bulk poll voting tier designed for massive contests and elections. Ensure the target chat or group invite link remains active, public, and open during fulfillment of order.",
  },
  {
    id: "wapv5",
    categoryId: "whatsapp-poll-votes",
    name: "WAPV5 WhatsApp Supreme Enterprise Poll Votes [Guaranteed VIP Priority]",
    serviceId: "26248",
    min: 100,
    max: 50000,
    rate: 10.00,
    refill: "60 Days Refill Guarantee",
    description: "Highest tier enterprise poll voting engineered for mission-critical corporate contests and high-stakes voting events. VIP priority execution with extended refill guarantee.",
    requiresLink: true,
    requiresComments: false,
    speed: "20k/day",
    startTime: "0-24 hours",
    notice: "Highest tier enterprise poll voting engineered for mission-critical corporate contests and high-stakes voting events. Ensure the target chat or group invite link remains active, public, and open during fulfillment of order.",
  },
  {
    id: "wacf1",
    categoryId: "whatsapp-channel-followers",
    name: "WACF1 WhatsApp Channel Followers [Instant / Non-Drop]",
    serviceId: "WA_CF_01",
    min: 100,
    max: 10000,
    rate: 2.50,
    refill: "30 Days Refill Guarantee",
    description: "Instant channel followers with non-drop guarantee. Real WhatsApp accounts. Channel must be public and invite link active.",
    requiresLink: true,
    requiresComments: false,
    speed: "5k/day",
    startTime: "0-2 hours",
    notice: "Ensure your WhatsApp channel invite link is active, public, and allows new followers. Do not reset or revoke your invite link while your order is processing.",
  },
  {
    id: "wacf2",
    categoryId: "whatsapp-channel-followers",
    name: "WACF2 WhatsApp Channel Followers [High Quality / Fast Speed]",
    serviceId: "WA_CF_02",
    min: 200,
    max: 25000,
    rate: 3.00,
    refill: "30 Days Refill Guarantee",
    description: "High-quality channel followers with fast delivery speed. Real accounts with active engagement. Channel must be public.",
    requiresLink: true,
    requiresComments: false,
    speed: "10k/day",
    startTime: "0-2 hours",
    notice: "Ensure your WhatsApp channel invite link is active, public, and allows new followers. Do not reset or revoke your invite link while your order is processing.",
  },
  {
    id: "wacf3",
    categoryId: "whatsapp-channel-followers",
    name: "WACF3 WhatsApp Channel Followers [Kenyan Target / Active Audience]",
    serviceId: "WA_CF_03",
    min: 100,
    max: 5000,
    rate: 5.50,
    refill: "60 Days Refill Guarantee",
    description: "Kenyan-targeted active audience channel followers. High retention with local engagement. Channel must be public.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-12 hours",
    notice: "Ensure your WhatsApp channel invite link is active, public, and allows new followers. Do not reset or revoke your invite link while your order is processing.",
  },
  {
    id: "wapr1",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WAPR1 WhatsApp Channel Post Reactions [Instant Turbo / All Emoji Mix]",
    serviceId: "26249",
    min: 50,
    max: 10000,
    rate: 1.50,
    refill: "No refill",
    description: "Lightning-fast server dispatch completing deliveries in under 1 minute. All emoji mix reactions for WhatsApp channel posts.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr2",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WAPR2 WhatsApp Channel Post Reactions [Targeted Specific Emoji Emoji Pack]",
    serviceId: "26250",
    min: 100,
    max: 20000,
    rate: 2.00,
    refill: "No refill",
    description: "Targeted specific emoji reactions for WhatsApp channel posts. Choose your preferred emoji pack for precise engagement.",
    requiresLink: true,
    requiresComments: false,
    speed: "30k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-money",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 💵 ]",
    serviceId: "26251",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant money bag emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-skull",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 💀 ]",
    serviceId: "26252",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant skull emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-cash",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 💸 ]",
    serviceId: "26253",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant cash emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-vomit",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 🤮 ]",
    serviceId: "26254",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant vomit emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-heartbreak",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 💔 ]",
    serviceId: "26255",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant heartbreak emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-flex",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 💪 ]",
    serviceId: "26256",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant flex emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-dislike",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 👎 ]",
    serviceId: "26257",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant dislike emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-poop",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 💩 ]",
    serviceId: "26258",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant poop emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-middle",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 🖕 ]",
    serviceId: "26259",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant middle finger emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-wow",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 😮 ]",
    serviceId: "26260",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant wow emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-angry",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 😡 ]",
    serviceId: "26261",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant angry emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-cool",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 😎 ]",
    serviceId: "26262",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant cool emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-clap",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 👏 ]",
    serviceId: "26263",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant clap emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-party",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 🎉 ]",
    serviceId: "26264",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant party emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-trophy",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 🏆 ]",
    serviceId: "26265",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant trophy emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-fire",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 🔥 ]",
    serviceId: "26266",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant fire emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-pray",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 🙏 ]",
    serviceId: "26267",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant pray emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-sad",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 😥 ]",
    serviceId: "26268",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant sad emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-shocked",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 😲 ]",
    serviceId: "26269",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant shocked emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-laugh",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 😂 ]",
    serviceId: "26270",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant laugh emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-love",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ ❤️ ]",
    serviceId: "26271",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant heart emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-thumbsup",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions [ 👍 ]",
    serviceId: "26272",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant thumbs up emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "wapr-random",
    categoryId: "whatsapp-channel-post-reactions-instant-server-complete-in-1-minute",
    name: "WhatsApp Channel Post Emoji Reactions | Random Mix [👍❤️😂😲😥🙏]",
    serviceId: "26273",
    min: 50,
    max: 100000,
    rate: 0.3162,
    refill: "No refill",
    description: "Instant random mix emoji reactions for WhatsApp channel posts. Ultra-fast delivery in under 1 minute.",
    requiresLink: true,
    requiresComments: false,
    speed: "50k/day",
    startTime: "0-1 minute",
    notice: "Lightning-fast server dispatch completing deliveries in under 1 minute. Ensure the target WhatsApp channel post link is direct, public, and accessible.",
  },
  {
    id: "waprs1",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WAPRS1 WhatsApp Channel Post Reactions [Budget Eco Tier / Gradual Pace]",
    serviceId: "26274",
    min: 100,
    max: 50000,
    rate: 0.80,
    refill: "No refill",
    description: "Economical slow server fulfillment designed for natural-looking growth over time. Budget-friendly gradual pace reactions for WhatsApp channel posts.",
    requiresLink: true,
    requiresComments: false,
    speed: "5k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs2",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WAPRS2 WhatsApp Channel Post Reactions [Economy Stable Pack / Natural Delivery]",
    serviceId: "26275",
    min: 200,
    max: 100000,
    rate: 1.00,
    refill: "30 Days Refill Guarantee",
    description: "Economy stable pack with natural delivery pace for WhatsApp channel post reactions. Designed for organic-looking engagement at a lower cost.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-48 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-money",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 💵 ]",
    serviceId: "26276",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant money bag emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-skull",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 💀 ]",
    serviceId: "26277",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant skull emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-cash",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 💸 ]",
    serviceId: "26278",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant cash emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-vomit",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 🤮 ]",
    serviceId: "26279",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant vomit emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-heartbreak",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 💔 ]",
    serviceId: "26280",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant heartbreak emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-flex",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 💪 ]",
    serviceId: "26281",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant flex emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-dislike",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 👎 ]",
    serviceId: "26282",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant dislike emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-poop",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 💩 ]",
    serviceId: "26283",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant poop emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-middle",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 🖕 ]",
    serviceId: "26284",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant middle finger emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-wow",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 😮 ]",
    serviceId: "26285",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant wow emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-angry",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 😡 ]",
    serviceId: "26286",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant angry emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-cool",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 😎 ]",
    serviceId: "26287",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant cool emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-clap",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 👏 ]",
    serviceId: "26288",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant clap emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-party",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 🎉 ]",
    serviceId: "26289",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant party emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-trophy",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 🏆 ]",
    serviceId: "26290",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant trophy emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-fire",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 🔥 ]",
    serviceId: "26291",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant fire emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-pray",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 🙏 ]",
    serviceId: "26292",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant pray emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-sad",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 😥 ]",
    serviceId: "26293",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant sad emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-shocked",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 😲 ]",
    serviceId: "26294",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant shocked emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-laugh",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 😂 ]",
    serviceId: "26295",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant laugh emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-love",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ ❤️ ]",
    serviceId: "26296",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant heart emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-thumbsup",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions [ 👍 ]",
    serviceId: "26297",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant thumbs up emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "waprs-random",
    categoryId: "whatsapp-channel-post-reactions-cheap-slow-server",
    name: "WhatsApp Channel Post Emoji Reactions | Random Mix [👍❤️😂😲😥🙏]",
    serviceId: "26298",
    min: 100,
    max: 100000,
    rate: 0.2874,
    refill: "No refill",
    description: "Instant random mix emoji reactions for WhatsApp channel posts. Slow server gradual delivery.",
    requiresLink: true,
    requiresComments: false,
    speed: "2k/day",
    startTime: "0-24 hours",
    notice: "Economical slow server fulfillment designed for natural-looking growth over time. Ensure the target WhatsApp channel post link is public and active before submitting your order.",
  },
  {
    id: "wapaf-laugh",
    categoryId: "whatsapp-channel-auto-future-post-reactions",
    name: "WhatsApp Channel Auto Post Reactions [😂]",
    serviceId: "26300",
    min: 100,
    max: 100000,
    rate: 21.6,
    refill: "No refill",
    description: "High-quality profile auto reactions for WhatsApp channel future posts. HQ profiles, 10K/day delivery, future 500 posts coverage.",
    requiresLink: true,
    requiresComments: false,
    speed: "10k/day",
    startTime: "0-24 hours",
    notice: "Ensure your WhatsApp channel is public and active for auto future post reactions. HQ profiles deliver high retention.",
  },
  {
    id: "wapaf-love",
    categoryId: "whatsapp-channel-auto-future-post-reactions",
    name: "WhatsApp Channel Auto Post Reactions [❤️]",
    serviceId: "26301",
    min: 100,
    max: 100000,
    rate: 21.6,
    refill: "No refill",
    description: "High-quality profile auto reactions for WhatsApp channel future posts. HQ profiles, 10K/day delivery, future 500 posts coverage.",
    requiresLink: true,
    requiresComments: false,
    speed: "10k/day",
    startTime: "0-24 hours",
    notice: "Ensure your WhatsApp channel is public and active for auto future post reactions. HQ profiles deliver high retention.",
  },
  {
    id: "wapaf-thumbsup",
    categoryId: "whatsapp-channel-auto-future-post-reactions",
    name: "WhatsApp Channel Auto Post Reactions [👍]",
    serviceId: "26302",
    min: 100,
    max: 100000,
    rate: 21.6,
    refill: "No refill",
    description: "High-quality profile auto reactions for WhatsApp channel future posts. HQ profiles, 10K/day delivery, future 500 posts coverage.",
    requiresLink: true,
    requiresComments: false,
    speed: "10k/day",
    startTime: "0-24 hours",
    notice: "Ensure your WhatsApp channel is public and active for auto future post reactions. HQ profiles deliver high retention.",
  },
  {
    id: "wapaf-mix",
    categoryId: "whatsapp-channel-auto-future-post-reactions",
    name: "WhatsApp Channel Auto Post Reactions | Mix [🙏👍😂👏🎉🔥🏆❤️😮]",
    serviceId: "26303",
    min: 100,
    max: 100000,
    rate: 3.0,
    refill: "No refill",
    description: "Random mix auto reactions for WhatsApp channel future posts. HQ profiles, 10K/day delivery, future 25 posts coverage.",
    requiresLink: true,
    requiresComments: false,
    speed: "10k/day",
    startTime: "0-24 hours",
    notice: "Ensure your WhatsApp channel is public and active for auto future post reactions. HQ profiles deliver high retention.",
  },
  {
    id: "ig-followers",
    categoryId: "instagram",
    name: "Instagram Followers [Refill/Country Targeted]",
    serviceId: "25933",
    min: 50,
    max: 500000,
    rate: 9.8,
    refill: "30 Days Refill Guarantee",
    description: "Real followers with refill guarantee. Country targeting available at checkout. Profile must be public.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "ig-likes",
    categoryId: "instagram",
    name: "Instagram Likes",
    serviceId: "25934",
    min: 10,
    max: 100000,
    rate: 0.75,
    refill: "No refill",
    description: "Instant likes on posts and reels. High-quality accounts with profile pictures.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "ig-comments",
    categoryId: "instagram",
    name: "Instagram Comments",
    serviceId: "25935",
    min: 5,
    max: 5000,
    rate: 3.5,
    refill: "No refill",
    description: "Custom or random comments. Leave your comment text in the order notes or select random option.",
    requiresLink: true,
    requiresComments: true,
  },
  {
    id: "ig-reels",
    categoryId: "instagram",
    name: "Instagram Reels Views",
    serviceId: "25936",
    min: 100,
    max: 1000000,
    rate: 0.35,
    refill: "No refill",
    description: "Reels views with high retention. Works on all public reels.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "fb-followers",
    categoryId: "facebook",
    name: "Facebook Page Followers",
    serviceId: "25937",
    min: 50,
    max: 200000,
    rate: 7.2,
    refill: "30 Days Refill Guarantee",
    description: "Real Facebook page followers. Page must be public and have content.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "fb-likes",
    categoryId: "facebook",
    name: "Facebook Profile Likes",
    serviceId: "25938",
    min: 10,
    max: 50000,
    rate: 0.9,
    refill: "No refill",
    description: "Likes on Facebook profile pictures. Instant delivery.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "fb-reactions",
    categoryId: "facebook",
    name: "Facebook Post Reactions",
    serviceId: "25939",
    min: 10,
    max: 10000,
    rate: 1.1,
    refill: "No refill",
    description: "Mixed reactions (Like, Love, Haha, Wow, Sad, Angry) on posts.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "fb-views",
    categoryId: "facebook",
    name: "Facebook Video Views",
    serviceId: "25940",
    min: 100,
    max: 500000,
    rate: 0.55,
    refill: "No refill",
    description: "Video views with good retention. Public video link required.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "tt-views",
    categoryId: "tiktok",
    name: "TikTok Views [KES 10 tu promo]",
    serviceId: "25941",
    min: 100,
    max: 5000000,
    rate: 0.25,
    refill: "No refill",
    description: "TikTok views at unbeatable price. Instant delivery. Public video required.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "tt-followers",
    categoryId: "tiktok",
    name: "TikTok Non-Drop Followers",
    serviceId: "25942",
    min: 50,
    max: 200000,
    rate: 11.0,
    refill: "60 Days Refill Guarantee",
    description: "High-quality non-drop followers. Profile must be public.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "tt-live",
    categoryId: "tiktok",
    name: "TikTok Live Stream Viewers",
    serviceId: "25943",
    min: 50,
    max: 5000,
    rate: 15.0,
    refill: "No refill",
    description: "Live viewers for 30 minutes per 1000 ordered. Start live stream before ordering.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "tg-members",
    categoryId: "telegram",
    name: "Telegram Channel Members",
    serviceId: "25944",
    min: 100,
    max: 50000,
    rate: 9.0,
    refill: "30 Days Refill Guarantee",
    description: "Real Telegram channel subscribers. Channel must be public or have join request enabled.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "tg-views",
    categoryId: "telegram",
    name: "Telegram Post Views",
    serviceId: "25946",
    min: 100,
    max: 100000,
    rate: 0.4,
    refill: "No refill",
    description: "Post views from real accounts. Fast delivery.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "tg-polls",
    categoryId: "telegram",
    name: "Telegram Poll Votes",
    serviceId: "25947",
    min: 50,
    max: 10000,
    rate: 0.8,
    refill: "No refill",
    description: "Poll votes from real accounts. Share the poll link and specify the option to vote.",
    requiresLink: true,
    requiresComments: true,
  },
  {
    id: "gm-reviews",
    categoryId: "google-maps",
    name: "Google Maps 5-Star Custom Reviews",
    serviceId: "25948",
    min: 5,
    max: 500,
    rate: 25.0,
    refill: "No refill",
    description: "Custom written reviews from local guides. High-quality, 5-star ratings. Business must be public.",
    requiresLink: true,
    requiresComments: true,
  },
  {
    id: "gm-guide",
    categoryId: "google-maps",
    name: "Google Maps Local Guide Feedback",
    serviceId: "25949",
    min: 5,
    max: 200,
    rate: 35.0,
    refill: "No refill",
    description: "Reviews from verified Local Guides with review history. Trusted and high-quality.",
    requiresLink: true,
    requiresComments: true,
  },
  {
    id: "gm-saves",
    categoryId: "google-maps",
    name: "Google Maps Place Saves & Directions",
    serviceId: "25950",
    min: 50,
    max: 10000,
    rate: 0.9,
    refill: "No refill",
    description: "Place saves and direction requests from real accounts.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "x-twf1",
    categoryId: "x-twitter",
    name: "TWF1 Twitter Followers [NFT]",
    serviceId: "25951",
    min: 100,
    max: 5000,
    rate: 15.0,
    refill: "No refill",
    description: "NFT-themed followers. Non-drop guarantee. Profile must be public.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "x-twlikes",
    categoryId: "x-twitter",
    name: "TWL14 Twitter Likes",
    serviceId: "25952",
    min: 20,
    max: 4000,
    rate: 7.0,
    refill: "No refill",
    description: "Real likes on tweets. Instant delivery.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "x-twf56",
    categoryId: "x-twitter",
    name: "TWF56 Twitter Followers [Less drop]",
    serviceId: "25953",
    min: 500,
    max: 500000,
    rate: 30.0,
    refill: "30 Days Refill Guarantee",
    description: "High-quality followers with less drop rate. Profile must be public.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "x-twlive",
    categoryId: "x-twitter",
    name: "TWLIVE Twitter Live Viewers [30 MINUTES]",
    serviceId: "25954",
    min: 100,
    max: 2500,
    rate: 18.0,
    refill: "No refill",
    description: "Live viewers for 30 minutes. Start your live stream before ordering.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "x-twcomments",
    categoryId: "x-twitter",
    name: "TWC3 Twitter Comment [CUSTOM] [Crypto bot]",
    serviceId: "25955",
    min: 10,
    max: 2000,
    rate: 5.5,
    refill: "No refill",
    description: "Custom comments or crypto bot generated comments. Provide your comment text in the order notes.",
    requiresLink: true,
    requiresComments: true,
  },
  {
    id: "x-mentions",
    categoryId: "x-twitter",
    name: "Twitter Mentions",
    serviceId: "25956",
    min: 50,
    max: 10000,
    rate: 12.0,
    refill: "No refill",
    description: "Custom mentions from real accounts. Provide the mention text and target tweet.",
    requiresLink: true,
    requiresComments: true,
  },
  {
    id: "x-poll",
    categoryId: "x-twitter",
    name: "Twitter Poll Votes",
    serviceId: "25957",
    min: 50,
    max: 10000,
    rate: 0.6,
    refill: "No refill",
    description: "Poll votes on active polls. Share the poll link and specify the option to vote.",
    requiresLink: true,
    requiresComments: true,
  },
  {
    id: "x-retweets",
    categoryId: "x-twitter",
    name: "Twitter Retweets",
    serviceId: "25958",
    min: 10,
    max: 50000,
    rate: 1.5,
    refill: "No refill",
    description: "Real retweets from active accounts. Public tweet required.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "x-space",
    categoryId: "x-twitter",
    name: "Twitter Space Listeners",
    serviceId: "25959",
    min: 50,
    max: 5000,
    rate: 12.0,
    refill: "No refill",
    description: "Live listeners for Twitter Spaces. Start your space before ordering.",
    requiresLink: true,
    requiresComments: false,
  },
  {
    id: "x-views",
    categoryId: "x-twitter",
    name: "Twitter Views Country Targeted [US/Denmark]",
    serviceId: "25960",
    min: 1000,
    max: 1000000,
    rate: 0.15,
    refill: "No refill",
    description: "Country-targeted views (US / Denmark). Select target country at checkout.",
    requiresLink: true,
    requiresComments: false,
  },
];

export const TICKER_ITEMS = [
  "🔥 TikTok Views — KES 10 tu! Instant delivery.",
  "⚡ Lipa na M-Pesa. Instant delivery guaranteed.",
  "🚀 YouTube Monetizable Subscribers — 100% real.",
  "💬 Join our WhatsApp Channel for daily promo codes!",
  "🎯 Instagram Followers with Refill — Drop-free guarantee.",
  "🌟 Happy Hour: -5% OFF all orders for the next 30 minutes!",
];

export const NOTIFICATIONS = [
  { id: 1, title: "Happy Hour Active", message: "5% discount on all orders! Use code HAPPY5 at checkout.", time: "2 min ago", type: "promo" },
  { id: 2, title: "New Service Available", message: "Telegram Poll Votes are now live. Check them out!", time: "1 hour ago", type: "update" },
  { id: 3, title: "Payment Success", message: "Your M-Pesa top-up of KES 1,000 was successful.", time: "3 hours ago", type: "success" },
];

export interface SidebarItem {
  label: string;
  icon?: string;
  href?: string;
  trigger?: "login" | "register";
  active?: boolean;
  children?: SidebarItem[];
}

export const SIDEBAR_ITEMS: SidebarItem[] = [
  { label: "New Order", href: "/order", icon: "🛒", active: true },
  { label: "Blog & News", href: "/blog", icon: "💬" },
  { label: "Sign Up", href: "/order#", icon: "📑", trigger: "register" },
  { label: "Sign In", href: "/order#", icon: "🔑", trigger: "login" },
  {
    label: "WhatsApp",
    icon: "🟢",
    children: [
      { label: "WhatsApp - Channel Followers", href: "/order/whatsapp-channel-followers", icon: "👥" },
      { label: "WhatsApp - Poll Votes ᴺᴱᵂ", href: "/order/whatsapp-poll-votes", icon: "📊" },
      { label: "WhatsApp - Channel Post Reactions [Instant Server | Complete In 1 Minute] ᴺᴱᵂ", href: "/order/whatsapp-channel-post-reactions-instant-server-complete-in-1-minute", icon: "⚡" },
      { label: "WhatsApp - Channel Post Reactions [Cheap Slow Server] ᴺᴱᵂ", href: "/order/whatsapp-channel-post-reactions-cheap-slow-server", icon: "🐢" },
      { label: "WhatsApp - Channel Auto Future Post Reactions ᴺᴱᵂ", href: "/order/whatsapp-channel-auto-future-post-reactions", icon: "🤖" },
      { label: "Legacy Services", href: "/order/whatssapp", icon: "🛒" },
    ],
  },
];

export const FOOTER_LINKS = {
  information: [
    { label: "Download App (.APK)", href: "https://dl.dropboxusercontent.com/scl/fi/uymbqkprrdua7k9ezoscs/app-debug.apk?rlkey=j32q53f061yla9sk665leihge&dl=1" },
    { label: "How It Works", href: "/how-it-works" },
    { label: "Why Choose Us", href: "/why-choose-us" },
    { label: "Reseller & API", href: "/reseller-and-api" },
    { label: "Contact Us", href: "/contact-us" },
    { label: "FAQ", href: "/faq" },
  ],
  quickActions: [
    { label: "🛒 New Order", href: "/order" },
    { label: "💳 Add Funds", href: "/pay" },
    { label: "📦 My Orders", href: "/orders/all" },
  ],
  support: [
    { label: "💬 Join WhatsApp Channel", href: "https://whatsapp.com/channel/0029Vb5nZqF6hENwDaWEPG3u" },
    { label: "🤝 Talk to Us (Direct WhatsApp)", href: "https://wa.link/cvhal8" },
    { label: "📜 Terms of Service", href: "/terms-of-service" },
    { label: "🔒 Privacy Policy", href: "/privacy-policy" },
  ],
};

export function getServiceById(id: string) {
  return ORDER_SERVICES.find((s) => s.id === id);
}

export function getServicesByCategory(categoryId: string) {
  return ORDER_SERVICES.filter((s) => s.categoryId === categoryId);
}
